### PR TITLE
适配不同社区不同账号鉴权

### PR DESCRIPTION
**Pull request by Kaede10**

### CODE REVIEW

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Review by zhongjun2 — APPROVED** [review]

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>dt覆盖率</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/66fb93d75f8d41f0a1082bbf4770f5a9/cf5574b7193c42098f21f560dafcf8eb">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>dt覆盖率</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/66fb93d75f8d41f0a1082bbf4770f5a9/a6daf2709f0f45fba807c214eb5de361">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>2.29994%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/66fb93d75f8d41f0a1082bbf4770f5a9/99823653b02f4b1087631eb68298587b">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>2.29975%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/66fb93d75f8d41f0a1082bbf4770f5a9/8c26535f49254761b12d328677a97fc0">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>2.29975%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/66fb93d75f8d41f0a1082bbf4770f5a9/38147544aef04319a979f2f816fd763b">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>2.29975%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/datastat-server/291/291_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/66fb93d75f8d41f0a1082bbf4770f5a9/8c26535f49254761b12d328677a97fc0">点击跳转</a></td>
</tr>
</table>

**Pull request closed without merging**
